name: Build images

on: push

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Dockerfiler (with push)
      if: github.ref == 'refs/heads/master'
      run: make run
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
        REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Run Dockerfiler (no push)
      if: github.ref != 'refs/heads/master'
      run: make dry-run
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
        REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
